### ISSUE TITLE
Allow Direct Linking to Sessions

### ISSUE THREAD

**Issue by bittersweetryan** [midwestjs/website#16]
Are there any plans to allow direct linking to sessions?  Would be nice if there was a route handler to allow midwestjs.com/speakers/Modern-UI-Development-With-Node.js which would automatically launch the modal with the sessions description.

You could have a pretty simple and naive implementation in a few lines of JS that would allow users to link to `midwestjs.com/speakers/#/<sessionid>`.  This approach comes with a few caveats: the person doing the linking would need to know their session's ID and google wouldn't index these pages:

```javascript
(function( window, $, undefined ){

    //actually call the modal, provided the element exists
    function openModalOnLoad( id ){
        var el = $( id );

        if( el.length && el.modal ){
            el.modal();
        }
    }

    //helper function to make sure the url conforms to /#/<sessionid>
    function parseHash( hash ){
        var hashParts = hash.split( '/' );

        if( hashParts.length !== 2 && hashParts[0] !== '#'){
            return;
        }

        return hashParts.join( '' );
    }

    $( function(){

        //this could be safe checked as well.
        var hash = window.location.hash;

        if( hash ){
            //will be undefined if the hash isn't in the right format
            var id = parseHash( hash );

            if( id ){
                openModalOnLoad( id );
            }
        }
    });


}( window, window.jQuery ));
```

**Comment by bobbywarner** [comment]
@bittersweetryan I guess I don't see a lot of people using this feature if it was added, but we can certainly add it if it's needed.  What's the use-case?  Do you just want to link to your talk somewhere else online?  Please let me know.

**Comment by staticnull** [comment]
It would allow us from the @midwest_js account to link to a session in a tweet and promote the session before the conference.

**Comment by staticnull** [comment]
Created a pull request for this...
https://github.com/midwestjs/website/pull/18

Seems to be working with no JS errors after a little tweaking. Feel free to iterate to make it better.

**Comment by bobbywarner** [comment]
This is now done. Thanks @staticnull
