### ISSUE TITLE
Add links/popups to speaker info from the Schedule page

### ISSUE THREAD

**Issue by JamesMGreene** [midwestjs/website#6]
Please consider adding links/popups to speaker info from the Schedule page. It's a nicety for speakers and attendees alike.

**Comment by kentcdodds** [comment]
@bobbywarner I like the look of you closing this issue. Means you're working on the website :-) #excited :D

**Comment by bobbywarner** [comment]
@kentcdodds This was done by Will Buck last year, ha! :)  I just never closed it, or do you think something else is needed?

**Comment by kentcdodds** [comment]
No, I just liked seeing activity on the repo. That's all I meant :-)

**Comment by bobbywarner** [comment]
@kentcdodds Ah, cool!  Thanks again for all your help on this last year!  Was pretty easy to update for everything this year!!! :)

**Comment by kentcdodds** [comment]
:+1:
